### ISSUE TITLE
Deploy project bsc network fail

### ISSUE THREAD

**Issue by HuangLeFei** [subquery/ethereum-subql-starter#7]
# indexer service runtime error

```
{"level":"info","timestamp":"2023-05-25T09:10:50.744Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"subql-node","message":"Current @subql/node-ethereum version is 2.2.2"}
{"level":"info","timestamp":"2023-05-25T09:10:52.254Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"indexer","message":"indexer manager start"}
{"level":"error","timestamp":"2023-05-25T09:10:52.305Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"dictionary","payload":{"type":"error","name":"Error","message":"No indexer found for chainId 56 in the network!","stack":"Error: No indexer found for chainId 56 in the network!\n    at authHttpLink (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@subql/apollo-links/dist/auth-http-link/authHttpLink.js:15:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DictionaryService.init (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@subql/node-core/dist/indexer/dictionary.service.js:127:24)\n    at async DictionaryService.init (/usr/local/lib/node_modules/@subql/node-ethereum/dist/indexer/dictionary.service.js:43:9)\n    at async InstanceWrapper.useFactory [as metatype] (/usr/local/lib/node_modules/@subql/node-ethereum/dist/indexer/fetch.module.js:78:21)\n    at async Injector.instantiateClass (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@nestjs/core/injector/injector.js:334:37)\n    at async callback (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@nestjs/core/injector/injector.js:48:30)\n    at async Injector.resolveConstructorParams (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@nestjs/core/injector/injector.js:122:24)\n    at async Injector.loadInstance (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@nestjs/core/injector/injector.js:52:9)\n    at async Injector.loadProvider (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@nestjs/core/injector/injector.js:74:9)"},"message":"Failed to resolve network dictionary"}
{"level":"info","timestamp":"2023-05-25T09:10:52.335Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"api.ethereum","message":"Api host: bnb.api.onfinality.io, method: wss"}
{"level":"info","timestamp":"2023-05-25T09:10:52.345Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"api.ethereum","message":"Api host: bsc-dataseed3.ninicoin.io, method: https"}
{"level":"info","timestamp":"2023-05-25T09:10:52.805Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"store","message":"Historical state is enabled"}
{"level":"error","timestamp":"2023-05-25T09:10:53.038Z","pid":7,"hostname":"subquery-18133-indexer-deployment-65df995cd9-qqq8w","category":"subql-node","payload":{"type":"error","name":"Error","message":"Try to record new deployment failed, unable to find last processed height from metadata","stack":"Error: Try to record new deployment failed, unable to find last processed height from metadata\n    at ProjectService.syncDeployments (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@subql/node-core/dist/indexer/project.service.js:194:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ProjectService.ensureMetadata (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@subql/node-core/dist/indexer/project.service.js:170:9)\n    at async ProjectService.init (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/@subql/node-core/dist/indexer/project.service.js:67:13)\n    at async bootstrap (/usr/local/lib/node_modules/@subql/node-ethereum/dist/init.js:42:9)"},"message":"Node failed to start"}

```
# project.yaml
```yaml
specVersion: "1.0.0"

name: "UpgradeProfit"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "[UpgradeProfit]"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for BSC this is 56
  # https://chainlist.org/chain/56
  chainId: "56"
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint: ["https://bnb.api.onfinality.io/rpc?apikey=9859916d-a5b4-417b-81c1-18a47bce32a1"]
  #  - https://bsc-dataseed1.binance.org
  #  - https://bnb.api.onfinality.io/rpc?apikey=9859916d-a5b4-417b-81c1-18a47bce32a1
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://gx.api.subquery.network/sq/subquery/bsc-dictionary"

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since BSC is a layer-2 that is compatible
    startBlock: 	28334803 # The block on which the Binance-Peg Ethereum token was deployed
    options:
      # Must be a key of assets
      abi: upgradeProfit
      address: "0x35249A85fADBC793cA89a486541881aB5911a4a3" # this is the contract address for Binance-Peg Ethereum Token https://bscscan.com/address/0x2170ed0880ac9a755fd29b2688956bd959f933f8
    assets:
      upgradeProfit:
        file: "./abis/upgradeProfit.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransaction
          kind: ethereum/TransactionHandler # We use ethereum handlers since BSC is a layer-2 that is compatible
          filter:
            ## The function can either be the function fragment or signature
            # function: '0x095ea7b3'
            # function: '0x7ff36ab500000000000000000000000000000000000000000000000000000000'
            function: upgradeProfit(uint256 amount)
        - handler: handleLog
          kind: ethereum/LogHandler # We use ethereum handlers since BSC is a layer-2 that is compatible
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - UpgradeProfitEvent(address indexed account, uint256 amount, uint256 fundAmount)
              # - WithdrawalEvent(uint256 indexed txId, address indexed account, uint256 amount)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"

```

![image](https://github.com/subquery/ethereum-subql-starter/assets/21329868/673777c1-9dc2-4873-b6c4-15d9f3b2136b)
